function [maxPCCsAgainstRandBarcodes] = calc_max_PCCs_against_rand_barcodes_with_same_len(barcode, randomBarcodes, barcodeIsCircularTF)
    % Calculate maximum PCCs
    shouldRescaleTF = true;
    import CBT.ExpComparison.Core.GrossCcorr.ccorr_all_based_max_cc;
    maxPCCsAgainstRandBarcodes = cellfun(...
        @(randomBarcode) ...
            ccorr_all_based_max_cc(barcode, randomBarcode, barcodeIsCircularTF, shouldRescaleTF), ...
        randomBarcodes ...
    );
end