function [] = add_contig_assembly_menu(hMenuParent, tsCA)
    hMenuContigAssembly = uimenu('Parent', hMenuParent, 'Label', 'Contig Assembly');
    uimenu(...
        'Parent', hMenuContigAssembly, ...
        'Label', 'Run contig assignment', ...
        'Callback', @(~, ~) CA.run_contig_assignment(tsCA));
    uimenu(...
        'Parent', hMenuContigAssembly, ...
        'Label', 'Run contig assignment (Older)', ...
        'Callback', @(~, ~) CA.run_contig_assignment_older(tsCA));
    uimenu(...
        'Parent', hMenuContigAssembly, ...
        'Label', 'Run tree assembly method', ...
        'Callback', @(~, ~) CA.TreeMethod.run_tree_method(tsCA))
    uimenu(...
        'Parent', hMenuContigAssembly, ...
        'Label', 'Run free energy method', ...
        'Callback', @(~, ~) CA.FreeEnergyMethod.run_free_energy_method(tsCA))
    hMenuContigAssemblyErik = uimenu(...
        'Parent', hMenuContigAssembly, ...
        'Label', 'Erik''s Contig Assembly');
    uimenu(...
        'Parent', hMenuContigAssemblyErik, ...
        'Label', 'Place Single Contig', ...
        'Callback', @(~, ~) CA.Old.run_single_contig_placement(tsCA))
    uimenu(...
        'Parent', hMenuContigAssemblyErik, ...
        'Label', 'Place Contigs', ...
        'Callback', @(~, ~) CA.Old.run_contig_placement(tsCA))
end