function [] = add_autobarcoder_menu(hMenuParent, tsAB, settings)
    import AB.UI.run_movie_to_kymos;
    hMenuAB = uimenu('Parent', hMenuParent, 'Label', 'Movie to Kymos');
    uimenu(...
        'Parent', hMenuAB, ...
        'Label', 'Run movie to kymos', ...
        'Callback', @(~, ~) run_movie_to_kymos(tsAB, settings));
end