function codeCheckTable = check_code_for_all_deps(depFilePaths)
    filepathColName = 'filepath';
    colNames = {filepathColName, 'message', 'fix', 'line', 'column'};
    try
        codeCheckStructsForDeps = cellfun(@(depFilePath) ...
            checkcode(depFilePath,'-struct'), ...
            depFilePaths, ...
            'UniformOutput', false);
        import Fancy.Utils.merge_structs;
        codeCheckStructsForDeps = cellfun(@(info2) ...
            arrayfun(@(s) merge_structs(struct(filepathColName, depFilePath), s), info2), ...
            codeCheckStructsForDeps, ...
            'UniformOutput', false);
        codeCheckTable = struct2table(vertcat(codeCheckStructsForDeps{:}));
    catch
        codeCheckTable = cell2table(cell(0, length(colNames)), 'VariableNames', colNames);
    end
end