function uicontrolDefaults = get_matlab_uicontrol_defaults(uiControlStyle, uiControlString)
    % GET_MATLAB_UICONTROL_DEFAULTS - gets the default values for
    %   properties for a uicontrol of a given style
    %
    % Inputs:
    %   uiControlStyle: (optional; defaults to 'pushbutton')
    %     String containing the value for the Style property of the
    %     uicontrol, with the following options: 
    %     'pushbutton', 'togglebutton', 'checkbox', 'radiobutton',
    %     'edit', 'text', 'slider', 'listbox', 'popupmenu'
    %
    %  uiControlString: (optional...
    %    defaults to '' -- but that is invalid for popupmenu)
    %     String containing the value for the String property of the
    %      uicontrol
    %
    % Output:
    %  uicontrolDefaults:
    %    A struct where field names are names of uicontrol
    %    properties and values are the default values for the
    %    uicontrol that Matlab uses
    %
    %  Note that the following property is not in the struct
    %   because the default value for it is system dependent:
    %  'FontSize'
    %
    % Authors:
    %   Saair Quaderi
    if nargin < 1
        uiControlStyle = 'pushbutton';
    elseif not(isempty(uiControlStyle))
        validateattributes(uiControlStyle, {'char'}, {'vector'}, 1);
        uiControlStyle = lower(uiControlStyle);
    end
    if nargin < 2
        uiControlString = '';
        % Note popupmenu ultimately requires a non-empty string
    elseif not(isempty(uiControlString))
        validateattributes(uiControlString, {'char'}, {'vector'}, 2);
    end
    switch uiControlStyle
        case 'listbox'
            uiControlValue = 1;
        case 'popupmenu'
            uiControlValue = 1;
        otherwise
            uiControlValue = 0;
    end
     % Note 'FontSize' default is system dependent
    uicontrolDefaults = struct(...
        'Style', uiControlStyle,...
        'String', uiControlString,...
        'Value', uiControlValue,...
        'Position', [20, 20, 60, 20],...
        'Visible', 'on',...
        'BackgroundColor', [.94, .94, .94],...
        'ForegroundColor', [0, 0, 0],...
        'CData', [],...
        'Units', 'pixels',...
        'FontName', 'Helvetica',...
        'FontUnits', 'points',...
        'FontWeight', 'normal',...
        'FontAngle', 'normal',...
        'HorizontalAlignment', 'center',...
        'Callback', '',...
        'ButtonDownFcn', '',...
        'KeyPressFcn', '',...
        'KeyReleaseFcn', '',...
        'Enable', 'on',...
        'TooltipString', '',...
        'UIContextMenu', gobjects(0,0),...
        'Selected', 'off',...
        'SelectionHighlight', 'on',...
        'Interruptible', 'on',...
        'BusyAction', 'queue',...
        'HitTest', 'on',...
        'BeingDeleted', 'off',...
        'CreateFcn', '',...
        'DeleteFcn', '',...
        'Tag', '',...
        'UserData', [],...
        'HandleVisibility', 'on',...
        'Max', 1,...
        'Min', 0,...
        'SliderStep', [0.01, 0.10],...
        'ListboxTop', 1);
end
 