CREATE TABLE meltmapschema.Videos (
	video_id integer not null unique,
	filename varchar,
	file_format varchar(8),
	video_date date,
	video_time time without time zone,
	experimenter varchar(64),
	microscope varchar(64),
	software varchar(64),
	lamp_type varchar(64),
	lamp_setting double precision,
	lamp_power_milliwatts double precision,
	dichroic varchar(64),
	neutral_density_filter varchar(64),
	objective varchar(64),
	camera varchar(64),
	pixel_size_microns double precision,
	gain double precision,
	conversion_gain double precision,
	camera_temp_degs_below_freezing double precision,
	frames_per_second double precision,
	exposure_time_milliseconds double precision,
	chuck varchar(64),
	driving_gas varchar(64),
	device varchar(64),
	device_material varchar(64),
	channel_width_nanometers double precision,
	channel_depth_nanometers double precision,
	dna varchar(64),
	dye varchar(64),
	dna_to_dye_ratio double precision,
	salt varchar(64),
	salt_concentration double precision,
	bme_concentration double precision,
	other varchar,
	notes varchar,
	PRIMARY KEY (video_id)
);