function [posEndCounts, posEndCountsPreCut] = count_cut_positions(barcodeLens, barcodeFlipTFs, barcodeCircShifts)
    alignedPosVectCells = arrayfun(...
        @(barcodeLen, flipTF, circShift) ...
            flip(circshift(linspace(0, 1, barcodeLen), circShift, 2), flipTF + 1),...
        barcodeLens,...
        barcodeFlipTFs,...
        barcodeCircShifts,...
        'UniformOutput', false);
    alignedPosMat = cell2mat(alignedPosVectCells);
    endsMat = (alignedPosMat == 0) | (alignedPosMat == 1);
    posEndCounts = sum(endsMat)';
    posEndCountsPreCut = sum(circshift(endsMat, -1, 2) & endsMat)';
end