function [] = set_raw_kymo_data(dbmODW, rawKymos, rawKymoFilepaths, pixelsWidths_bps)
    rawKymoFileStructs = cellfun( ...
        @(rawKymo, rawKymoFilepath) ...
            struct(...
                'locs', [], ...
                'regions', [], ...
                'averagedImg',  rawKymo', ...
                'fileName', rawKymoFilepath), ...
        rawKymos, rawKymoFilepaths, ...
        'UniformOutput', false);
    fileMoleculeStructs = cellfun( ...
        @(rawKymo) ...
            { ...
                struct(...
                    'frames', [], ...
                    'kymograph',  rawKymo, ...
                    'information', [], ...
                    'passesFilters', true ...
                )...
            }, ...
        rawKymos, ...
        'UniformOutput', false);

    dbmODW.DBMMainstruct.fileCell = rawKymoFileStructs;
    dbmODW.DBMMainstruct.fileMoleculeCell = fileMoleculeStructs;
    dbmODW.verify_thresholds();


    if nargin >= 4
        numFiles = length(rawKymoFilepaths);
        fileIdxs = (1:numFiles)';
        dbmODW.set_molecule_src_pixel_widths_in_bps(fileIdxs, pixelsWidths_bps);
    end
end