function [aborted, timeframeKymoMolLenMat, inputFilepath] = try_prompt_timeframe_kymo_mol_len_mat()
    timeframeKymoMolLenMat = [];
    inputFilepath = '';
    % TODO: consider depricating this functionality
    
    % Input file containing matrix of estimated molecule lengths...
    %  across different timeframes (rows)
    %  across different kymographs (columns)
    % Historically these were generated by DBM's menu option:
    %  "Calculate file statistics" > "Calculate (Save)" 
    import Fancy.AppMgr.AppResourceMgr;
    appRsrcMgr = AppResourceMgr.get_instance();
    appDirpath = appRsrcMgr.get_app_dirpath();
    defaultInputDirpath = appDirpath;
    defaultFilename = 'testL.txt';
    defaultFilepath = fullfile(defaultInputDirpath, defaultFilename);
    [inputFilename, inputDirpath] = uigetfile('*.txt', 'Select Txt Mat of Timeframe Molecule Len per Kymo', defaultFilepath);
    aborted = isequal(inputDirpath, 0);
    if aborted
        return;
    end
    inputFilepath = fullfile(inputDirpath, inputFilename);
    timeframeKymoMolLenMat = load(inputFilepath);
end