function [] = run_svd(tsSVD)
    hPanel = tsSVD.create_tab('Run SVD');

    hParamPanel = uipanel(...
        'Parent', hPanel, ...
        'Title', 'Parameters', ...
        'Units', 'normalized', ...
        'Position', [0.5 0.5 0.49 0.49] ...
        );
    hFilepathPanel = uipanel(...
        'Parent', hPanel, ...
        'Title', 'Filepaths', ...
        'Units', 'normalized', ...
        'Position', [0.01 0.3 0.98 0.2] ...
        );

    %Parameter Selection
    %LCMA:
    hLCMAParamSubPanel = uipanel(...
        'Parent', hParamPanel, ...
        'Units', 'normalized', ...
        'Position', [0.01 0.01 0.99 0.98], ...
        'Visible', 'off'...
        );
    hLCMAParamText1 = uicontrol(...
        'Parent', hLCMAParamSubPanel,...
        'Style', 'text',...
        'String', 'Band Width (pixels):',...
        'Units', 'normalized', ...
        'Position', [0.01 0.75 0.6 0.2] ...
        );
    hLCMAParamText2 = uicontrol(...
        'Parent', hLCMAParamSubPanel,...
        'Style', 'text',...
        'String', 'LCMA Length (pixels):',...
        'Units', 'normalized', ...
        'Position', [0.01 0.6 0.6 0.2] ...
        );
    hLCMAParamText3 = uicontrol(...
        'Parent', hLCMAParamSubPanel,...
        'Style', 'text',...
        'String', 'LCMA Threshold (cost):',...
        'Units', 'normalized', ...
        'Position', [0.01 0.45 0.6 0.2] ...
        );
    hLCMAParamText4 = uicontrol(...
        'Parent', hLCMAParamSubPanel,...
        'Style', 'text',...
        'String', 'Number of Best Bands:',...
        'Units', 'normalized', ...
        'Position', [0.01 0.3 0.6 0.2] ...
        );
    hLCMAParamBox1 = uicontrol (...
        'Parent', hLCMAParamSubPanel,...
        'Style', 'edit',...
        'String', '4',...
        'HorizontalAlignment', 'Right',...
        'FontSize', 9,...
        'Units', 'normalized', ...
        'Position', [0.75 0.85 0.2 0.12] ...
        );
    hLCMAParamBox2 = uicontrol (...
        'Parent', hLCMAParamSubPanel,...
        'Style', 'edit',...
        'String', '3',...
        'HorizontalAlignment', 'Right',...
        'FontSize', 9,...
        'Units', 'normalized', ...
        'Position', [0.75 0.70 0.2 0.12] ...
        );
    hLCMAParamBox3 = uicontrol (...
        'Parent', hLCMAParamSubPanel,...
        'Style', 'edit',...
        'String', '0.3',...
        'HorizontalAlignment', 'Right',...
        'FontSize', 9,...
        'Units', 'normalized', ...
        'Position', [0.75 0.55 0.2 0.12] ...
        );
    hLCMAParamBox4 = uicontrol (...
        'Parent', hLCMAParamSubPanel,...
        'Style', 'edit',...
        'String', '8',...
        'HorizontalAlignment', 'Right',...
        'FontSize', 9,...
        'Units', 'normalized', ...
        'Position', [0.75 0.40 0.2 0.12] ...
        );
    %MVM:
    hMVMParamSubPanel = uipanel(...
        'Parent', hParamPanel, ...
        'Units', 'normalized', ...
        'Position', [0.01 0.01 0.99 0.98], ...
        'Visible', 'off'...
        );
    hMVMParamText1 = uicontrol(...
        'Parent', hMVMParamSubPanel,...
        'Style', 'text',...
        'String', 'Max. Stretch (Optional, pixels):',...
        'Units', 'normalized', ...
        'Position', [0.03 0.75 0.8 0.2], ...
        'HorizontalAlignment', 'Left'...
        );
    hMVMParamBox1 = uicontrol (...
        'Parent', hMVMParamSubPanel,...
        'Style', 'edit',...
        'String', 'Inf',...
        'HorizontalAlignment', 'Right',...
        'FontSize', 9,...
        'Units', 'normalized', ...
        'Position', [0.75 0.85 0.2 0.12] ...
        );

    %Method Selection
    hMethodsRadioButtonGroup = uibuttongroup(...
        'Parent', hPanel, ...
        'Title', 'Method', ...
        'Units', 'normalized', ...
        'Position', [0.01 0.5 0.48 0.49] ...
        );

    hRadioButton1 = uicontrol(...
        'Parent', hMethodsRadioButtonGroup, ...
        'Tag', '1', ...
        'Style', 'radiobutton', ...
        'String', 'Dynamic Time Warping (DTW)', ...
        'Units', 'normalized', ...
        'Position', [0.03 0.80 1 0.2] ...
        );
    hRadioButton2 = uicontrol(...
        'Parent', hMethodsRadioButtonGroup, ...
        'Tag', '2',...
        'Style', 'radiobutton', ...
        'String', 'Minimum Variance Matching (MVM)', ...
        'Units', 'normalized', ...
        'Position', [0.03 0.60 1 0.2] ...
        );
    hRadioButton3 = uicontrol(...
        'Parent', hMethodsRadioButtonGroup, ...
        'Tag', '3',...
        'Style', 'radiobutton', ...
        'String', 'Adapted LCMA Segment Detection', ...
        'Units', 'normalized', ...
        'Position', [0.03 0.40 1 0.2] ...
        );
    hRadioButton4 = uicontrol(...
        'Parent', hMethodsRadioButtonGroup, ...
        'Tag', '4',...
        'Style', 'radiobutton', ...
        'String', 'Linear Assignment Problem (LAP)', ...
        'Units', 'normalized', ...
        'Position', [0.03 0.20 1 0.2] ...
        );

    hRadioButton5 = uicontrol(...
        'Parent', hMethodsRadioButtonGroup, ...
        'Tag', '5',...
        'Style', 'radiobutton', ...
        'String', 'Profile hidden Markov model (pHMM)', ...
        'Units', 'normalized', ...
        'Position', [0.03 0.00 1 0.2] ...
        );
    %Filepath Selection
    hTextLabelSelectFile1 = uicontrol(...
        'Parent', hFilepathPanel,...
        'Style', 'text',...
        'String', 'Barcode 1:',...
        'Units', 'normalized', ...
        'Position', [0.01 0.65 0.12 0.24] ...
        );
    hTextLabelSelectFile2 = uicontrol(...
        'Parent', hFilepathPanel,...
        'Style', 'text',...
        'String', 'Barcode 2:',...
        'Units', 'normalized', ...
        'Position', [0.01 0.25 0.12 0.24] ...
        );
    hEditSelectFile1 = uicontrol (...
        'Parent', hFilepathPanel,...
        'Style', 'edit',...
        'HorizontalAlignment', 'Left',...
        'Units', 'normalized', ...
        'Position', [0.14 0.6 0.4 0.32] ...
        );
    hEditSelectFile2 = uicontrol(...
        'Parent', hFilepathPanel,...
        'Style', 'edit',...
        'HorizontalAlignment', 'Left',...
        'Units', 'normalized', ...
        'Position', [0.14 0.2 0.4 0.32] ...
        );

    hBtnSelectFile1 = uicontrol(...
        'Parent', hFilepathPanel,...
        'Tag', '1', ...
        'Style', 'pushbutton',...
        'String', 'Get File',...
        'Units', 'normalized', ...
        'Position', [0.55 0.6 0.14 0.32] ...
        );
    hBtnSelectFile2 = uicontrol(...
        'Parent', hFilepathPanel,...
        'Tag', '2', ...
        'Style', 'pushbutton',...
        'String', 'Get File',...
        'Units', 'normalized', ...
        'Position', [0.55 0.2 0.14 0.32] ...
        );
    hTextLabelSelectLength1 = uicontrol(...
        'Parent', hFilepathPanel,...
        'Style', 'text',...
        'String', 'Size (kbp)',...
        'Units', 'normalized', ...
        'Position', [0.70 0.65 0.12 0.24] ...
        );
    hTextLabelSelectLength2 = uicontrol(...
        'Parent', hFilepathPanel,...
        'Style', 'text',...
        'String', 'Size (kbp)',...
        'Units', 'normalized', ...
        'Position', [0.70 0.25 0.12 0.24] ...
        );
    hEditSelectLength1 = uicontrol (...
        'Parent', hFilepathPanel,...
        'Style', 'edit',...
        'HorizontalAlignment', 'Left',...
        'Units', 'normalized', ...
        'Position', [0.84 0.6 0.15 0.32] ...
        );
    hEditSelectLength2 = uicontrol(...
        'Parent', hFilepathPanel,...
        'Style', 'edit',...
        'HorizontalAlignment', 'Left',...
        'Units', 'normalized', ...
        'Position', [0.84 0.2 0.15 0.32] ...
        );
    %Checkboxes:
    hEditNeighborWeight = uicontrol(...
        'Parent', hPanel,...
        'Style', 'edit',...
        'Units', 'normalized',...
        'Position', [0.59 0.2 0.08 0.046],...
        'Visible', 'off',...
        'FontSize', 9,...
        'String', '10',...
        'HorizontalAlignment', 'Right'...
        );

    hNeighborWeightTextLabel = uicontrol(...
        'Parent', hPanel,...
        'Style', 'text',...
        'Units', 'normalized',...
        'Position', [0.19 0.16 0.4 0.08],...
        'Visible', 'off',...
        'String', 'Distance (pixels):',...
        'HorizontalAlignment', 'Right'...
        );

    hCheckboxUseNeighbors = uicontrol(...
        'Parent', hPanel,...
        'Style', 'checkbox',...
        'Units', 'normalized',...
        'Position', [0.032 0.182 0.36 0.08],...
        'String', 'Use Neighbor-weighted Costs'...
        );

    hCheckboxUsePCC = uicontrol(...
        'Parent', hPanel,...
        'Style', 'checkbox',...
        'Units', 'normalized',...
        'Position', [0.032 0.122 0.36 0.08],...
        'String', 'Use Pearson Correlation Score'...
        );


    %Start Button:
    hBtnStart = uicontrol(...
        'Parent', hPanel, ...
        'Style', 'pushbutton', ...
        'String', 'Compare', ...
        'Units', 'normalized', ...
        'Position', [0.824 0.18 0.16 0.08] ...
        );

    import SVD.UI.update_selected_file;
    set(hBtnSelectFile1, 'Callback', @(~, ~) update_selected_file(hEditSelectFile1));
    set(hBtnSelectFile2, 'Callback', @(~, ~) update_selected_file(hEditSelectFile2));

    import SVD.UI.toggle_pcc_usage;
    set(hCheckboxUsePCC, 'Callback', @(hSource, ~) toggle_pcc_usage(hSource, hCheckboxUseNeighbors, hEditNeighborWeight, hNeighborWeightTextLabel));

    import SVD.UI.toggle_neighbor_usage;
    set(hCheckboxUseNeighbors, 'Callback', @(~, ~) toggle_neighbor_usage(hEditNeighborWeight, hNeighborWeightTextLabel, hCheckboxUsePCC));

    
    import SVD.UI.execute;
    set(hBtnStart, 'Callback', @(~, ~) ...
        execute(...
            tsSVD,...
            hEditSelectFile1, hEditSelectFile2, ...
            hEditSelectLength1, hEditSelectLength2, ...
            hRadioButton1, hRadioButton2, hRadioButton3, hRadioButton4, hRadioButton5, ...
            hMVMParamBox1, ...
            hLCMAParamBox1, hLCMAParamBox2, hLCMAParamBox3, hLCMAParamBox4,...
            hCheckboxUseNeighbors, hEditNeighborWeight, hCheckboxUsePCC));

    import SVD.UI.on_selected_method_change;
    set(hMethodsRadioButtonGroup, 'SelectionChangedFcn', @(~, eventData) on_selected_method_change(eventData, hMVMParamSubPanel, hLCMAParamSubPanel));
end
