function [] = async_prompt_kymo_analysis_method(hFig, fn_callback)
    hBtnGroup = uibuttongroup( ...
        'Parent', hFig, ...
        'Units', 'Normalized', ...
        'Position', [0.05 0.3 0.9 0.6]);

    uicontrol(...
        'Style', 'Radio', ...
        'Parent', hBtnGroup, ...
        'HandleVisibility', 'off', ...
        'String', 'Thresholding (faster)', ...
        'Tag', 'basic_otsu_edge_detection', ...
        'Units', 'Normalized', ...
        'Position', [0.075 0.6, 0.9, 0.2]);

    uicontrol(...
        'Style', 'Radio', ...
        'Parent', hBtnGroup, ...
        'HandleVisibility', 'off', ...
        'String', 'Double Error Function (more precise)', ...
        'Tag', 'double_tanh_edge_detection', ...
        'Units', 'Normalized', ...
        'Position', [0.075 0.3 0.9 0.2]);

    uicontrol(...
        'Parent', hFig, ...
        'Style', 'pushbutton', ...
        'String', 'Calculate', ...
        'Units', 'Normalized', ...
        'Position', [0.15 0.1 0.34 0.15], ...
        'Callback', @(~, ~) fn_callback(get_method_name_and_close_figure(hBtnGroup, hFig), false));

    uicontrol( ...
        'Parent', hFig, ...
        'Style', 'pushbutton', ...
        'String', 'Calculate (Save)', ...
        'Units', 'Normalized', ...
        'Position', [0.51 0.1 0.34 0.15], ...
        'Callback', @(~, ~) fn_callback(get_method_name_and_close_figure(hBtnGroup, hFig), true));

    set(hFig,'Visible','on');

    function methodName = get_method_name_and_close_figure(hButtonGroup, hFig)
        methodName = get(get(hButtonGroup,'SelectedObject'),'Tag');
        delete(hFig);
    end
end