function [] = add_elt_menu(hMenuParent, tsELT)
    if nargin < 2
        tsELT = [];
    end
    hMenuELT = uimenu( ...
        'Parent', hMenuParent, ...
        'Label', 'ELT');
    
    import ELT.UI.run_elt;
    uimenu( ...
        'Parent', hMenuELT, ...
        'Label', 'Run ELT', ...
        'Callback', @(~, ~) run_elt(tsELT));
end