function [pairings] = extract_pairings(clusterConsensusData)
    import Barcoding.Helpers.sanitize_barcodes;

    consensusStruct = clusterConsensusData.details.consensusStruct;
    barcodeStructsMap = consensusStruct.barcodeStructsMap;
    pairingKeys = keys(barcodeStructsMap);
    pairingKeys = pairingKeys(~cellfun(@isempty, strfind(pairingKeys, ',')));
    pairingStructs = cellfun(@(x) barcodeStructsMap(x), pairingKeys, 'UniformOutput', false);

    pairingBarcodes = cellfun(@(x) x.barcode, pairingStructs, 'UniformOutput', false);
    pairingBitmasks = cellfun(@(x) x.indexWeights > 0, pairingStructs, 'UniformOutput', false);
    pairingBarcodes = sanitize_barcodes(pairingBarcodes, pairingBitmasks);

    pairingParentsA =  cellfun(@(x) x.parents{1}, pairingStructs, 'UniformOutput', false);
    pairingParentsB =  cellfun(@(x) x.parents{2}, pairingStructs, 'UniformOutput', false);

    pairingParentsKeyA =  cellfun(@(x) x{1}, pairingParentsA, 'UniformOutput', false);
    pairingParentsKeyB =  cellfun(@(x) x{1}, pairingParentsB, 'UniformOutput', false);

    pairingParentsFlipTFA =  cellfun(@(x) x{2}, pairingParentsA, 'UniformOutput', false);
    pairingParentsFlipTFB =  cellfun(@(x) x{2}, pairingParentsB, 'UniformOutput', false);

    pairingParentsCircShiftA =  cellfun(@(x) x{3}, pairingParentsA, 'UniformOutput', false);
    pairingParentsCircShiftB =  cellfun(@(x) x{3}, pairingParentsB, 'UniformOutput', false);

    pairingParentsBarcodeStructA =  cellfun(@(x) barcodeStructsMap(x), pairingParentsKeyA, 'UniformOutput', false);
    pairingParentsBarcodeStructB =  cellfun(@(x) barcodeStructsMap(x), pairingParentsKeyB, 'UniformOutput', false);

    pairingParentsBarcodeA = cellfun(@(x) x.barcode, pairingParentsBarcodeStructA, 'UniformOutput', false);
    pairingParentsBarcodeB =  cellfun(@(x) x.barcode, pairingParentsBarcodeStructB, 'UniformOutput', false);

    pairingParentsBitmaskA = cellfun(@(x) x.indexWeights > 0, pairingParentsBarcodeStructA, 'UniformOutput', false);
    pairingParentsBitmaskB =  cellfun(@(x) x.indexWeights > 0, pairingParentsBarcodeStructB, 'UniformOutput', false);

    pairingParentsBarcodeA = sanitize_barcodes(pairingParentsBarcodeA, pairingParentsBitmaskA);
    pairingParentsBarcodeB = sanitize_barcodes(pairingParentsBarcodeB, pairingParentsBitmaskB);


    import Barcoding.Reorienting.reorient_circ_indices;
    pairingParentsAlignedBarcodeA = cellfun(@(barcode, flipTF, circShift) reorient_circ_indices(barcode, flipTF, circShift), pairingParentsBarcodeA, pairingParentsFlipTFA, pairingParentsCircShiftA, 'UniformOutput', false);
    pairingParentsAlignedBarcodeB = cellfun(@(barcode, flipTF, circShift) reorient_circ_indices(barcode, flipTF, circShift), pairingParentsBarcodeB, pairingParentsFlipTFB, pairingParentsCircShiftB, 'UniformOutput', false);

    pairings = cellfun(...
        @(...
            key,...
            keyParentA,...
            keyParentB,...
            barcode,...
            barcodeParentA,...
            barcodeParentB,...
            flipParentA,...
            flipParentB,...
            circShiftParentA,...
            circShiftParentB,...
            alignedBarcodeParentA,...
            alignedBarcodeParentB...
        )...
            struct(...
            'key', key,...
            'keyParentA', keyParentA,...
            'keyParentB', keyParentB,...
            'barcode', barcode,...
            'barcodeParentA', barcodeParentA,...
            'barcodeParentB', barcodeParentB,...
            'flipParentA', flipParentA,...
            'flipParentB', flipParentB,...
            'circShiftParentA', circShiftParentA,...
            'circShiftParentB', circShiftParentB,...
            'alignedBarcodeParentA', alignedBarcodeParentA,...
            'alignedBarcodeParentB', alignedBarcodeParentB...
            ),...
        pairingKeys,...
        pairingParentsKeyA,...
        pairingParentsKeyB,...
        pairingBarcodes,...
        pairingParentsBarcodeA,...
        pairingParentsBarcodeB,...
        pairingParentsFlipTFA,...
        pairingParentsFlipTFB,...
        pairingParentsCircShiftA,...
        pairingParentsCircShiftB,...
        pairingParentsAlignedBarcodeA,...
        pairingParentsAlignedBarcodeB,...
        'UniformOutput', false);
end