function [...
    alignedBarcodes, ...
    alignedBitmasks, ...
    clusterBarcodeKeys, ...
    clusterBarcodeAliases, ...
    otherBarcodeData, ...
    clusterBarcodeNums ...
] = extract_aligned_cluster_consensus_components(clusterConsensusData)
    consensusStruct = clusterConsensusData.details.consensusStruct;
    clusterBarcodeKeys = clusterConsensusData.clusterResultStruct.barcodeKeys;
    clusterBarcodeNums = str2double(clusterBarcodeKeys);

    inputs = consensusStruct.inputs;
    clusterBarcodeAliases = inputs.barcodeAliases(clusterBarcodeNums);
    otherBarcodeData = [];
    if isfield(inputs, 'otherBarcodeData')
        otherBarcodeData = inputs.otherBarcodeData(clusterBarcodeNums);
    end

    alignedBarcodes = clusterConsensusData.clusterResultStruct.alignedBarcodes;
    alignedBitmasks = clusterConsensusData.clusterResultStruct.alignedBarcodeBitmasks;
end