function [prestretchUntrustedEdgeLenUnrounded_pixels, prestretchPixelWidth_nm,psfSigmaWidth_nm,deltaCut] = get_prestretch_params(dbmSettingsStruct)
    if (nargin < 1) || isempty(dbmSettingsStruct)
        import OldDBM.General.SettingsWrapper;
        [dbmSettingsStruct] = SettingsWrapper.read_DBM_settings();
    end
    bitmaskSettings = dbmSettingsStruct.bitmasks;
    skipOverridePromptTF = isfield(bitmaskSettings, 'promptForBitmaskingParams') && (bitmaskSettings.promptForBitmaskingParams == 0);
    import Fancy.Utils.extract_fields;
    [psfSigmaWidth_nm, deltaCut, prestretchPixelWidth_nm] = extract_fields(bitmaskSettings,...
        {'PSF_width', 'DeltaCut', 'nmPerPixel'});

    import CBT.Consensus.Import.get_raw_px_edge_length;
    [ ...
        prestretchUntrustedEdgeLenUnrounded_pixels, ...
        ~, ...
        ~, ...
        prestretchPixelWidth_nm ...
        ] = get_raw_px_edge_length(...
            psfSigmaWidth_nm, ...
            deltaCut, ...
            prestretchPixelWidth_nm, ...
            skipOverridePromptTF);
end