function [eteSessionStruct ] = create_ete_session_struct(...
            stretchedConsensusBarcodes, ...
            isPlasmid, ...
            stretchedKbpsPerPixel, ...
            sameLengthTF, ...
            stretchFactors, ...
            meanZeroModelFftFreqMags, ...
            zeroModelKbpsPerPixel, ...
            numRandBarcodes, ...
            pValMat, ...
            maxPCCsMat, ...
            flipMat, ...
            shortShiftMat, ...
            longShiftMat, ...
            stretchFactorsMat, ...
            consensusBarcodeNames)

    eteSessionStruct.stretchedConsensusBarcodes = stretchedConsensusBarcodes;
    eteSessionStruct.isPlasmid=isPlasmid;
    eteSessionStruct.stretchedKbpsPerPixel = stretchedKbpsPerPixel;
    eteSessionStruct.sameLengthTF=sameLengthTF;
    eteSessionStruct.stretchFactors = stretchFactors;
    eteSessionStruct.meanZeroModelFftFreqMags = meanZeroModelFftFreqMags;
    eteSessionStruct.zeroModelKbpsPerPixel=zeroModelKbpsPerPixel;
    eteSessionStruct.numRandBarcodes = numRandBarcodes;
    eteSessionStruct.pValMat=pValMat;
    eteSessionStruct.maxPCCsMat=maxPCCsMat;
    eteSessionStruct.flipMat=flipMat;
    eteSessionStruct.shortShiftMat=shortShiftMat;
    eteSessionStruct.longShiftMat=longShiftMat;
    eteSessionStruct.stretchFactorsMat=stretchFactorsMat;
    eteSessionStruct.consensusBarcodeNames=consensusBarcodeNames;
end

