function [] = add_cbc_menu(hMenuParent, tsCBC)
    hMenuCBC = uimenu( ...
        'Parent', hMenuParent, ...
        'Label', 'CBC');
    
    import CBT.Consensus.run_consensing;
    uimenu( ...
        'Parent', hMenuCBC, ...
        'Label', 'Run Consensus Generation', ...
        'Callback', @(~, ~) run_consensing(tsCBC));
    
    import CBT.Consensus.Import.load_consensus_results;
    uimenu( ...
        'Parent', hMenuCBC, ...
        'Label', 'Load Consensus Results', ...
        'Callback', @(~, ~) load_consensus_results(tsCBC));
end