function [flipTF] = ccorr_all_based_flipcheck(...
        barcodeA, ...
        barcodeB, ...
        longerBarcodeIsCircularTF, ...
        shouldRescaleTF ...
        )
    import CBT.ExpComparison.Core.GrossCcorr.ccorr_all;
    [~, ~, flip, ~] = ccorr_all(...
        barcodeA, ...
        barcodeB, ...
        longerBarcodeIsCircularTF, ...
        shouldRescaleTF ...
        );
    flipTF = logical(flip);
end