function [] = disp_intensity_drop_warnings(rawKymoName,rawKymoFileIdxs, rawKymoFileMoleculeIdxs, rawKymos, moleculeMasks, kymoStatsStructs)
    largeDropNumKymoEndAreaFrames = 10;
    largeDropRatioThreshold = 0.65;

    if size(moleculeMasks,2)>size(moleculeMasks,1)
        moleculeMasks = moleculeMasks';
    end

    if size(rawKymos,2)>size(rawKymos,1)
        rawKymos = rawKymos';
    end
    bgIntensityApproxs = arrayfun(...
        @(kymoStatsStruct) ...
            kymoStatsStruct.meanNonMainMoleculePixelIntensity, ...
        kymoStatsStructs, ...
        'UniformOutput', false);
    import OldDBM.Kymo.Core.calc_end_over_start_intensity_ratio
    endOverStartIntensityRatio = cellfun( ...
        @(rawKymo, moleculeMask, bgIntensityApprox) ...
            calc_end_over_start_intensity_ratio(rawKymo, moleculeMask, bgIntensityApprox, largeDropNumKymoEndAreaFrames), ...
        rawKymos, moleculeMasks, bgIntensityApproxs ...
    );
    isLargeDrop = endOverStartIntensityRatio < largeDropRatioThreshold;
    if any(isLargeDrop)
        warningFileIdxs = rawKymoFileIdxs(isLargeDrop);
        warningFileMoleculeIdxs = rawKymoFileMoleculeIdxs(isLargeDrop);
        warningSrcFilenames = rawKymoName(warningFileIdxs);
        warningEndOverStartIntensityRatios = endOverStartIntensityRatio(isLargeDrop);
%         if ~isrow(warningEndOverStartIntensityRatios) % fix: check if this is a row
            warningEndOverStartIntensityRatios = warningEndOverStartIntensityRatios';
%         end

        warningTable = table( ...
            warningSrcFilenames, ...
            warningFileIdxs, ...
            warningFileMoleculeIdxs, ...
            warningEndOverStartIntensityRatios, ...
            'VariableNames', {'srcFilename', 'fileIdx', 'fileMoleculeIdx', 'endOverStartIntensityRatio'});
        warning('Large decreases in intensity detected!'); %TODO:
        disp(warningTable);
    end
end