function hGoPlottedBarcode = plot_barcode_intesity(hAxis, x, barcodeRegion, barcodeLineColor)
    cla(hAxis, 'reset');
    hGoPlottedBarcode = plot(hAxis, ...
        x(:), ...
        barcodeRegion(:), ...
        'LineWidth', 1.5, ...
        'Color', barcodeLineColor ...
    );
    hold(hAxis, 'on');
    xlabel(hAxis, 'Pixel (#)');
    ylabel(hAxis, 'Intensity');
    set(hAxis, ...
        'TickLength', [0 0], ...
        'TickDir', 'out' ...
    );
end