function [backgroundProfileStruct] = generate_background_profile(backgroundSampling, backgroundProfileConfidenceAlpha)
    probDistBackgroundAmplifiedSampling = fitdist(backgroundSampling, 'Normal');
    backgroundProfileConfidenceIntervals = paramci(probDistBackgroundAmplifiedSampling, 'Alpha', backgroundProfileConfidenceAlpha);
    backgroundProfileStruct = struct(...
        'confidenceAlpha', backgroundProfileConfidenceAlpha,...
        'meanLower', backgroundProfileConfidenceIntervals(1,1),...
        'meanUpper', backgroundProfileConfidenceIntervals(2,1),...
        'stdLower', backgroundProfileConfidenceIntervals(1,2),...
        'stdUpper', backgroundProfileConfidenceIntervals(2,2)...
    );
end