function [outlierScoresMatrixLowest] = extract_outlier_scores_matrix_lowest(outlierScoresMatrix, nLowest)
    import Fancy.Utils.cellify_rows;

    outlierScoresMatrixLowest = cellfun(...
        @(values) values(1:nLowest),...
        cellfun(...
            @(values) [sort(values(not(isnan(values))), 'ascend')'; NaN(nLowest, 1)],...
            cellify_rows(outlierScoresMatrix),...
            'UniformOutput', false),...
        'UniformOutput', false);
    outlierScoresMatrixLowest = [outlierScoresMatrixLowest{:}];
end