function [tableDataA, tableColMetadataA] = get_kymo_video_info()
    sqlQueryA = sprintf('SELECT %s FROM %s', ...
        strjoin({ ...
        'K.kymo_id', ...
        'K.video_id', ...
        'V.filename as video_filename', ...
        'driving_gas', ...
        'video_date', ...
        'video_time', ...
        'pixel_size_microns', ...
        'frames_per_second', ...
        'exposure_time_milliseconds', ...
        'lamp_power_milliwatts'}, ', '), ...
        'meltmapschema.kymos as K JOIN meltmapschema.videos as V ON K.video_id = V.video_id');
    
    import MeltmapDB.load_meltmap_conn_settings;
    meltmapConnSettings = load_meltmap_conn_settings();
    import MeltmapDB.connect_to_db;
    conn = connect_to_db(meltmapConnSettings);
    import MeltmapDB.run_sql_query;
    [tableDataA, tableColMetadataA] = run_sql_query(conn, sqlQueryA);

    conn.close();
    
    import MeltmapDB.matlabify_table_data;
    tableDataA = matlabify_table_data(tableDataA, tableColMetadataA);
end