function [] = generate_ete_ui(ts, eteSessionStruct)
    % generate ete ui

    import CBT.ExpComparison.UI.struct2vars
    struct2vars(eteSessionStruct)

    % TODO: redo the buttons and plots using code template
    %---Plot Stuff---
    % Create result image
    hTabBranchHist = ts.create_tab('Branch histogram');
    ts.select_tab(hTabBranchHist);
    hPanelBranchHist = uipanel('Parent', hTabBranchHist);

    % Plotting the p-value heat map
    hAxisPValHeatmap = axes(...
        'Parent', hPanelBranchHist, ...
        'Units', 'normalized', ...
        'Position', [0.1 0.25 0.83 0.7]);

    % Create the buttons and input boxes
    hBarcodeIdxEditboxA = uicontrol('Parent',hPanelBranchHist,...
        'Units','normalized',...
        'Position',[0.1 0.07 0.13 0.05],...
        'Style','edit',...
        'String','1');
    hBarcodeIdxEditboxB = uicontrol('Parent',hPanelBranchHist,...
        'Units','normalized',...
        'Position',[0.28 0.07 0.13 0.05],...
        'Style','edit',...
        'String','2');
    hBtnPlotBarcodes = uicontrol('Parent',hPanelBranchHist,...
        'Units','normalized',...
        'Position',[0.47 0.10 0.18 0.05],...
        'String','Plot barcodes');
    hBtnSaveBarcodeTxt = uicontrol('Parent',hPanelBranchHist,...
        'Units','normalized',...
        'Position',[0.47 0.04 0.18 0.05],...
        'String','Save barcode txt');
    hBtnSaveMatrixTxt = uicontrol('Parent',hPanelBranchHist,...
        'Units','normalized',...
        'Position',[0.75 0.07 0.18 0.05],...
        'String','Save p-value txt file');
    hSaveCCTxt = uicontrol('Parent',hPanelBranchHist,...
        'Units','normalized',...
        'Position',[0.75 0.01 0.18 0.05],...
        'String','Save cc txt file'...
        );
    hBtnSaveMatrixAvgTxt = uicontrol('Parent',hPanelBranchHist,...
        'Units','normalized',...
        'Position',[0.75 0.13 0.18 0.05],...
        'String','Save p-value mean');

   
    import CBT.ExpComparison.UI.plot_exp_vs_exp_barcodes;

    set(hBtnPlotBarcodes, 'Callback', @(~, ~) ...
            feval(@(barcodeIdxA, barcodeIdxB) ...
               CBT.ExpComparison.UI.plot_exp_vs_exp_barcodes( ...
                    barcodeIdxA, ...
                    barcodeIdxB, ...
                    stretchedConsensusBarcodes{barcodeIdxA}, ...
                    stretchedConsensusBarcodes{barcodeIdxB}, ...
                    consensusBarcodeNames{barcodeIdxA}, ...
                    consensusBarcodeNames{barcodeIdxB}, ...
                    stretchedKbpsPerPixel, ...
                    pValMat(barcodeIdxA, barcodeIdxB), ...
                    maxPCCsMat(barcodeIdxA, barcodeIdxB), ...
                    flipMat, ...
                    shortShiftMat, ...
                    longShiftMat, ...
                    stretchFactorsMat, ...
                    stretchFactors, ...
                    sameLengthTF ...
                ), ...
                str2double(get(hBarcodeIdxEditboxA, 'String')), ...
                str2double(get(hBarcodeIdxEditboxB, 'String'))));
    import CBT.ExpComparison.Export.export_barcode_comparison_txt_wrapper;
    set(hBtnSaveBarcodeTxt, 'Callback',  @(~, ~) ...
        feval(@(barcodeIdxA, barcodeIdxB) ...
            CBT.ExpComparison.Export.export_barcode_comparison_txt_wrapper( ...
                    barcodeIdxA, ...
                    barcodeIdxB, ...
                    stretchedConsensusBarcodes, ...
                    consensusBarcodeNames, ...
                    stretchedKbpsPerPixel, ...
                    pValMat, ...
                    maxPCCsMat, ...
                    flipMat, ...
                    shortShiftMat, ...
                    longShiftMat, ...
                    stretchFactorsMat, ...
                    stretchFactors, ...
                    sameLengthTF ...
                ), ...
            str2double(get(hBarcodeIdxEditboxA, 'String')), ...
            str2double(get(hBarcodeIdxEditboxB, 'String')) ...
            ));

    import CBT.ExpComparison.Export.export_exps_vs_exps_numeric_mat_txt;
    set(hBtnSaveMatrixTxt, 'Callback', @(~, ~) ...
        export_exps_vs_exps_numeric_mat_txt(...
            pValMat, ...
            consensusBarcodeNames, ...
            'P-value'));

    set(hSaveCCTxt, 'Callback', @(~, ~) ...
            export_exps_vs_exps_numeric_mat_txt(...
                maxPCCsMat, ...
                consensusBarcodeNames, ...
                'Cross-correlation'));

    import CBT.ExpComparison.Export.export_mean_sval_mat_mean_txt;
    set(hBtnSaveMatrixAvgTxt, 'Callback', @(~, ~) ...
        export_mean_sval_mat_mean_txt(pValMat, consensusBarcodeNames));

    import CBT.ExpComparison.UI.plot_pvalue_heatmap;
    plot_pvalue_heatmap(hAxisPValHeatmap, pValMat);
end