function [] = RA_Gui()
    % RA_GUI - - Result Analyzer (RA) GUI for
    %  predicting DNA barcodes, competitive binding, and comparing
    %   to experiments or CB theory barcodes from other sequences

    hFig = figure(...
        'Name',  'TvT Results', ...
        'Units', 'normalized', ...
        'OuterPosition', [0 0.05 1 0.95], ...
        'MenuBar', 'none', ...
        'ToolBar', 'figure');

    % function print_figure_image()
    %     import Fancy.UI.PseudoScreenshot.print_figure_image;
    %     print_figure_image(hFig);
    % end
    % fn_print_figure_image = @print_figure_image;

    import Fancy.UI.Toolbars.delete_all_other_toolbar_buttons;
    delete_all_other_toolbar_buttons(hFig, {...
        'Exploration.Pan';...
        'Exploration.ZoomOut';...
        'Exploration.ZoomIn';...
        'Standard.PrintFigure';...
        'Standard.SaveFigure'...
    });
    hPanel = uipanel(hFig);
    
    import Fancy.UI.FancyTabs.TabbedScreen;
    tsTvT = TabbedScreen(hPanel);

    import CBT.TheoryComparison.ResultAnalysis.UI.add_tvt_results_importer_in_panel;
    add_tvt_results_importer_in_panel(tsTvT);
end